get_forecasts_radar:
  target:
    entity:
      integration: irm_kmi
      domain: weather
  fields:
    include_past_forecasts:
      required: true
      default: false
      selector:
        boolean:
